FROM golang:1.23-alpine as builder
WORKDIR /app
COPY . .
RUN GOOS=linux CGO_ENABLED=0 go build -ldflags="-w -s" -o cli-test ./cmd/cli

FROM scratch
COPY --from=builder /app/cli-test .

ENTRYPOINT ["./cli-test"]
